version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
